### ISSUE TITLE
Error with Ruby ruby 2.7.0p0 and Pod 1.10.1

### ISSUE THREAD

**Issue by paxicocicd** [wonderpush/react-native-wonderpush#9]
Hello there!

I'm getting this two errors right here just at installing and building, using this versions of Pods (1.10.1) and Ruby (2.7.0p0)

```
.../ios/Pods/WonderPushExtension/WonderPushExtension/Sources/WPNotificationServiceExtension.m:130:59: No known class method for selector 'extract:'

.../ios/Pods/WonderPushExtension/WonderPushExtension/Sources/WPNotificationServiceExtension.m:256:34: No visible @interface for 'WPReportingData' declares the selector 'filledEventData:'
```

React Native: 0.63.4
React-native-wonderpush: ^2.0.2,
React-native-wonderpush-fcm: ^1.0.2,

**Comment by ofavre** [comment]
Hi,

Make sure that you are using the same version of the `WonderPush` and `WonderPushExtension` pods.

For `react-native-wonderpush` version 2.0.2, you should use version 4.0.1.
Edit your `ios/Podfile` so that it reads:

```
target 'WonderPushNotificationServiceExtension' do
  platform :ios, '10.0'

  # Pods for WonderPushNotificationServiceExtension
  pod 'WonderPushExtension', '4.0.1'
end
```
